GET http://localhost:3000/livros

####
GET http://localhost:3000/livros/6659ffb882f1dd2845bd3020


####

POST http://localhost:3000/livros
Content-Type: application/json

{
	"titulo": "o senhor dos aneis",
	"editora": "clasico",
	"paginas": 200,
	"valor": 10,
	"autor": "66820eb234e9ccd9bb07be74"
}

####
DELETE http://localhost:3000/livros/6659fe91ccc16b88f93cb529

#####

PUT http://localhost:3000/livros/665a0e9207b9466602f3e31b
Content-Type: application/json

{
	"titulo": "eeeee",
	"editora": "clasico",
	"paginas": 200,
	"valor": 10
}

#####

GET http://localhost:3000/autores



######

POST http://localhost:3000/autores
Content-Type: application/json

{
	"nome": "jrr token",
	"nacionalidade": "africa do sul"
}

#####
DELETE http://localhost:3000/autores/66820583b355a60d627e416a

###
POST http://localhost:3000/livros
Content-Type: application/json

{
	"titulo": "O Similarillion",
	"autor": "66820eb234e9ccd9bb07be74"
}


####
GET http://localhost:3000/livros/busca?editora=clasico